version: '3.1'
services:
  dbpostgres:
    image: postgres
    container_name: postgres-portfolio
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

# postgres 연결하기
# docker inspect 명령어를 이용해 IPAdress를 얻어낸다. ex)"IPAddress": "172.21.0.2"

