version: "3"
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-favres
    ports:
      - "13306:3306"
    environment: # -e 옵션
      - MYSQL_USER: mysql
      - MYSQL_PASSWORD : mysql
      - MYSQL_ROOT_PASSWORD: mysql
      - MYSQL_DATABASE: favres
    volumes:
      - ./mysql/data:/var/lib/mysql